FROM mcr.microsoft.com/playwright/python:v1.49.1-jammy

WORKDIR /app

# 额外系统依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl && \
    rm -rf /var/lib/apt/lists/*

# Python 依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "app.core.celery_app", "worker", "-l", "info", "-c", "2", "-Q", "crawl"]
